# Generated by Django 5.2 on 2025-05-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='events', to='events.tags'),
        ),
    ]
