# Generated by Django 5.2 on 2025-05-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='events', to='events.tags'),
        ),
    ]
